" Swap Back-space/Delete (interix)
set t_kb=
set t_kD=

" don't delete original file
set nobackup
set nowritebackup
set noswapfile

" no autoindent when pasting
set paste

" default for programming
set nowrap
