" Home/End/Delete key (interix)
set t_kh=[H
set t_@7=[F
set t_kD=

" don't delete original file
set nobackup
set nowritebackup
set noswapfile

" no autoindent when pasting
set paste

" default for programming
set nowrap
